ALTER TABLE T_SECTEUR ADD C_ID_SITE int;
ALTER TABLE T_SECTEUR ADD FOREIGN KEY (C_ID_SITE) REFERENCES T_SITE(C_ID);

ALTER TABLE T_SECTEUR ADD C_ID_USER int;
ALTER TABLE T_SECTEUR ADD FOREIGN KEY (C_ID_USER) REFERENCES T_USER(C_ID);
